ruby:
  config_file: .rubocop.yml
  exclude:
    -"config/initializers/wice_grid_config.rb"
scss:
  config_file: .scss-lint.yml
  exclude:
    -"app/assets/stylesheets/mixins.scss"
    -"app/assets/stylesheets/plugins/*"
