Agenda.find_or_create_by!(index: 1, title: 'SOFMÖ - sektionsordförande förklarar mötet öppnat')
Agenda.find_or_create_by!(index: 2, title: 'Tid och sätt för mötet')
Agenda.find_or_create_by!(index: 3, title: 'Val av mötesordförande')
Agenda.find_or_create_by!(index: 4, title: 'Val av mötessekreterare')
Agenda.find_or_create_by!(index: 5, title: 'Val av justerare tillika rösträknare tillika omfamnare')
Agenda.find_or_create_by!(index: 6, title: 'Justering av röstlängden')
Agenda.find_or_create_by!(index: 7, title: 'Adjungeringar')
Agenda.find_or_create_by!(index: 8, title: 'Mötesinformation')
Agenda.find_or_create_by!(index: 9, title: 'Godkännande av föredragningslista')
Agenda.find_or_create_by!(index: 10, title: 'Meddelanden')
Agenda.find_or_create_by!(index: 11, title: 'Styrelsens verksamhetsberättelse för 2016')
Agenda.find_or_create_by!(index: 12, title: 'Likabehandlingsutskottets verksamhetsberättelse för 2016')
Agenda.find_or_create_by!(index: 13, title: 'Bokslut för 2016')
Agenda.find_or_create_by!(index: 14, title: 'Revisionsberättelse för 2016')
Agenda.find_or_create_by!(index: 15, title: 'Beslut angående ansvarsfrihet för styrelsen 2016')
Agenda.find_or_create_by!(index: 16, title: 'Bokslutsdisposition för 2016')
Agenda.find_or_create_by!(index: 17, title: 'Revision av verksamhetsplan för 2017')
Agenda.find_or_create_by!(index: 18, title: 'Årets lärare')
Agenda.find_or_create_by!(index: 19, title: 'Stadfästande av fyllnadsval')
Agenda.find_or_create_by!(index: 20, title: 'Motion angående standardisering av reglementet')

prop = Agenda.find_or_create_by!(index: 21, title: 'Propositioner')
Agenda.find_or_create_by!(index: 1, parent: prop, title: 'Proposition angående rättelse av valförfarande - Andra läsningen')
Agenda.find_or_create_by!(index: 2, parent: prop, title: 'Proposition angående budgetrevidering för 2017')
Agenda.find_or_create_by!(index: 3, parent: prop, title: 'Proposition angående röda dagar')
Agenda.find_or_create_by!(index: 4, parent: prop, title: 'Proposition angående tidsfrist för likabehandlingsplan')
Agenda.find_or_create_by!(index: 5, parent: prop, title: 'Proposition angående jubeldespotens mandatperiod')
Agenda.find_or_create_by!(index: 6, parent: prop, title: 'Proposition angående styrelsens åligganden')
Agenda.find_or_create_by!(index: 7, parent: prop, title: 'Proposition angående ändringar i stadgar')
Agenda.find_or_create_by!(index: 8, parent: prop, title: 'Proposition angående ändringar och tillägg i policy för funktionärsförmåner')
Agenda.find_or_create_by!(index: 9, parent: prop, title: 'Proposition angående sammanslagning av Bilfonden och Sektionslokalsfonden')
Agenda.find_or_create_by!(index: 10, parent: prop, title: 'Proposition angående inköp av partytält')
Agenda.find_or_create_by!(index: 11, parent: prop, title: 'Proposition angående inköp av iZettle och tillhörande enheter')
Agenda.find_or_create_by!(index: 12, parent: prop, title: 'Proposition angående instiftande av policy för sektionens medlemskap')
Agenda.find_or_create_by!(index: 13, parent: prop, title: 'Proposition angående utskottsrapporter')

mot = Agenda.find_or_create_by!(index: 22, title: 'Motioner')
Agenda.find_or_create_by!(index: 1, parent: mot, title: 'Motion angående inköp av nya grillar')
Agenda.find_or_create_by!(index: 2, parent: mot, title: 'Motion angående policy för fyllnadsval')
Agenda.find_or_create_by!(index: 3, parent: mot, title: 'Motion angående policy för val')
Agenda.find_or_create_by!(index: 4, parent: mot, title: 'Motion angående moderation av diskussion på sektionsmöten')
Agenda.find_or_create_by!(index: 5, parent: mot, title: 'Motion angående val av nollningsfunktionärer')
Agenda.find_or_create_by!(index: 6, parent: mot, title: 'Motion angående policy för bilder')
Agenda.find_or_create_by!(index: 7, parent: mot, title: 'Motion angående inköp av skrivare')
Agenda.find_or_create_by!(index: 8, parent: mot, title: 'Motion angående inköp av kamerautrustning')
Agenda.find_or_create_by!(index: 9, parent: mot, title: 'Motion angående inköp av kylmonter till Hilbert Café')
Agenda.find_or_create_by!(index: 10, parent: mot, title: 'Motion angående omstrukturering av prylmästeriet')
Agenda.find_or_create_by!(index: 11, parent: mot, title: 'Motion angående omstrukturering av Kulturministeriet')
Agenda.find_or_create_by!(index: 12, parent: mot, title: 'Motion angående Vice ordförandens åligganden')
Agenda.find_or_create_by!(index: 13, parent: mot, title: 'Motion angående revidering av ekonomisk policy')
Agenda.find_or_create_by!(index: 14, parent: mot, title: 'Motion angående reglementesändringar rörande Kassörsutskottet')
Agenda.find_or_create_by!(index: 15, parent: mot, title: 'Motion angående namnbyte av resultatenheter')
Agenda.find_or_create_by!(index: 16, parent: mot, title: 'Motion angående äskning av pengar till sektionslokalerna')
Agenda.find_or_create_by!(index: 17, parent: mot, title: 'Motion angående F-sektionens arbetsmiljöarbete')
Agenda.find_or_create_by!(index: 18, parent: mot, title: 'Motion angående Likabehandlingsutskottets struktur')
Agenda.find_or_create_by!(index: 19, parent: mot, title: 'Motion angående F-sektionens likabehandlingspolicy')
Agenda.find_or_create_by!(index: 20, parent: mot, title: 'Motion angående arbetskläder till FNU')
Agenda.find_or_create_by!(index: 21, parent: mot, title: 'Motion angående inköp av värmeskåp')

funk = Agenda.find_or_create_by!(index: 23, title: 'Funktionärsval')
Agenda.find_or_create_by!(index: 1, parent: funk, title: 'Inspektor')
Agenda.find_or_create_by!(index: 2, parent: funk, title: 'Styrelseledamöter')
Agenda.find_or_create_by!(index: 3, parent: funk, title: 'Vice ordförande')
Agenda.find_or_create_by!(index: 4, parent: funk, title: 'Utbildningsminister')
Agenda.find_or_create_by!(index: 5, parent: funk, title: 'Prylmästare')
Agenda.find_or_create_by!(index: 6, parent: funk, title: 'Vice cafémästare')
Agenda.find_or_create_by!(index: 7, parent: funk, title: 'von Tänen-redaktör')
Agenda.find_or_create_by!(index: 8, parent: funk, title: 'Vice näringslivsansvarig')
Agenda.find_or_create_by!(index: 9, parent: funk, title: 'Projektledare FARAD')
Agenda.find_or_create_by!(index: 10, parent: funk, title: 'Studierådsordförande för teknisk fysik')
Agenda.find_or_create_by!(index: 11, parent: funk, title: 'Studierådsordförande för teknisk matematik')
Agenda.find_or_create_by!(index: 12, parent: funk, title: 'Studierådsordförande för teknisk nanovetenskap')
Agenda.find_or_create_by!(index: 13, parent: funk, title: 'Valberedningsledamöter')
Agenda.find_or_create_by!(index: 14, parent: funk, title: 'Valberedningssuppleanter')

Agenda.find_or_create_by!(index: 24, title: 'Övriga frågor')
Agenda.find_or_create_by!(index: 25, title: 'Frågan om F :s förträfflighet')
Agenda.find_or_create_by!(index: 26, title: 'Mötesordförandes fräckis')
Agenda.find_or_create_by!(index: 27, title: 'MOFMA - mötesordförande förklarar mötet avslutat')
