Agenda.find_or_create_by!(index: 1, title: 'SOFMÖ - sektionsordförande förklarar mötet öppnat')
Agenda.find_or_create_by!(index: 2, title: 'Tid och sätt för mötet')
Agenda.find_or_create_by!(index: 3, title: 'Val av mötesordförande')
Agenda.find_or_create_by!(index: 4, title: 'Val av mötessekreterare')
Agenda.find_or_create_by!(index: 5, title: 'Val av justerare tillika rösträknare tillika omfamnare')
Agenda.find_or_create_by!(index: 6, title: 'Justering av röstlängden')
Agenda.find_or_create_by!(index: 7, title: 'Adjungeringar')
Agenda.find_or_create_by!(index: 8, title: 'Mötesinformation')
Agenda.find_or_create_by!(index: 9, title: 'Godkännande av föredragningslista')
Agenda.find_or_create_by!(index: 10, title: 'Meddelanden')
Agenda.find_or_create_by!(index: 11, title: 'Fullmäktigeval')
Agenda.find_or_create_by!(index: 12, title: 'Redovisning av ledningens preliminära verksamhetsberättelse för 2017')
Agenda.find_or_create_by!(index: 13, title: 'Motion angående reglementet 2.0')

prop = Agenda.find_or_create_by!(index: 14, title: 'Propositioner')
Agenda.find_or_create_by!(index: 1, parent: prop, title: 'Proposition angående verksamhetsplan för 2018')
Agenda.find_or_create_by!(index: 2, parent: prop, title: 'Proposition angående budget för 2018')
Agenda.find_or_create_by!(index: 3, parent: prop, title: 'Proposition angående ändringar i stadgar - andra läsningen')
Agenda.find_or_create_by!(index: 4, parent: prop, title: 'Proposition angående stadgeändringar')
Agenda.find_or_create_by!(index: 5, parent: prop, title: 'Proposition angående sektionens värdegrund')
Agenda.find_or_create_by!(index: 6, parent: prop, title: 'Proposition angående sektionsmötesordförande')
Agenda.find_or_create_by!(index: 7, parent: prop, title: 'Proposition angående gratis sektionsblock för medlemmar')
Agenda.find_or_create_by!(index: 8, parent: prop, title: 'Proposition angående tidsbegränsning av äskningar ur fonder')
Agenda.find_or_create_by!(index: 9, parent: prop, title: 'Proposition angående ändringar i policy för funktionärsförmåner')
Agenda.find_or_create_by!(index: 10, parent: prop, title: 'Proposition angående ändringar i policy för val')
Agenda.find_or_create_by!(index: 11, parent: prop, title: 'Proposition angående förtydligande av val av Årets lärare')

motioner = Agenda.find_or_create_by!(index: 15, title: 'Motioner')
Agenda.find_or_create_by!(index: 1, parent: motioner, title: 'Motion angående sektionsmerch')
Agenda.find_or_create_by!(index: 2, parent: motioner, title: 'Motion angående slushmaskin')
Agenda.find_or_create_by!(index: 3, parent: motioner, title: 'Motion angående kassasystem och izettle')
Agenda.find_or_create_by!(index: 4, parent: motioner, title: 'Motion angående älgstaty')
Agenda.find_or_create_by!(index: 5, parent: motioner, title: 'Motion angående gungstolar')
Agenda.find_or_create_by!(index: 6, parent: motioner, title: 'Motion angående sektionsmormor')
Agenda.find_or_create_by!(index: 7, parent: motioner, title: 'Motion angående tv')
Agenda.find_or_create_by!(index: 8, parent: motioner, title: 'Motion angående bakisar')

funk = Agenda.find_or_create_by!(index: 16, title: 'Funktionärsval')
Agenda.find_or_create_by!(index: 1, parent: funk, title: 'Sektionsordförande')
Agenda.find_or_create_by!(index: 2, parent: funk, title: 'Sekreterare')
Agenda.find_or_create_by!(index: 3, parent: funk, title: 'Kassör')
Agenda.find_or_create_by!(index: 4, parent: funk, title: 'Överfös')
Agenda.find_or_create_by!(index: 5, parent: funk, title: 'Sanningsminister')
Agenda.find_or_create_by!(index: 6, parent: funk, title: 'Kulturminister')
Agenda.find_or_create_by!(index: 7, parent: funk, title: 'Sexmästare')
Agenda.find_or_create_by!(index: 8, parent: funk, title: 'Vice cafémästare')
Agenda.find_or_create_by!(index: 9, parent: funk, title: 'Näringslivsansvarig')
Agenda.find_or_create_by!(index: 10, parent: funk, title: 'Likabehandlingsordförande')
Agenda.find_or_create_by!(index: 11, parent: funk, title: 'Revisor')
Agenda.find_or_create_by!(index: 12, parent: funk, title: 'Revisorssuppleant')
Agenda.find_or_create_by!(index: 13, parent: funk, title: 'Köksmästare')
Agenda.find_or_create_by!(index: 14, parent: funk, title: 'Hofmästare')
Agenda.find_or_create_by!(index: 15, parent: funk, title: 'Pubmästare')
Agenda.find_or_create_by!(index: 16, parent: funk, title: 'Idrottsförman')
Agenda.find_or_create_by!(index: 17, parent: funk, title: 'Reisemeister')
Agenda.find_or_create_by!(index: 18, parent: funk, title: 'Vice kassör med sexmästeriansvar')
Agenda.find_or_create_by!(index: 19, parent: funk, title: 'Vice kassör med nollningsansvar')
Agenda.find_or_create_by!(index: 20, parent: funk, title: 'Sektionshärold')
Agenda.find_or_create_by!(index: 21, parent: funk, title: 'Sångarstridsförman')
Agenda.find_or_create_by!(index: 22, parent: funk, title: 'Vice näringslivsansvarig')
Agenda.find_or_create_by!(index: 23, parent: funk, title: 'Von tänen-redaktör')

Agenda.find_or_create_by!(index: 17, title: 'Övriga frågor')
Agenda.find_or_create_by!(index: 18, title: 'Frågan om F:s förträfflighet')
Agenda.find_or_create_by!(index: 19, title: 'Mötesordförandes fräckis')
Agenda.find_or_create_by!(index: 20, title: 'MOFMA - mötesordförande förklarar mötet avslutat')
